---
category: [ Data Center,Design,BGP ]
title: Redundant Layer-3-Only Data Center Fabrics
sort_field: name

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

bottom: |
  <hr/>
  ## More Information

  If you’re building a cloud infrastructure, explore the webinars from the
  [Cloud Infrastructure](http://www.ipspace.net/Roadmap/Cloud_computing_webinars) and
  [Software-Defined Data Centers](https://www.ipspace.net/SDDC) series,
  in particular the [Designing Cloud Infrastructure](http://www.ipspace.net/Designing_Private_Cloud_Infrastructure)
  and [Designing Active-Active and Disaster Recovery Data Centers](http://www.ipspace.net/Designing_Active-Active_and_Disaster_Recovery_Data_Centers).

  If you’re building a data center fabric, start with the
  [Leaf-and-Spine Fabric Architectures and Designs](http://www.ipspace.net/Leaf-and-Spine_Fabric_Architectures)
  webinar and use the information from
  [Data Center Fabric Architectures](http://www.ipspace.net/Data_Center_Fabrics)
  webinar when selecting vendors and equipment.

  You get all the above webinars with the [ipSpace.net subscription](http://www.ipspace.net/Subscription).

  {{ next }}
