comments:
- date: 20 February 2008 15:54
  html: What could be the real world scenario using this trick?
  id: '907808840109628329'
  image: https://bp0.blogger.com/_-1iA_boOgBo/R6ThTIRaOXI/AAAAAAAAADs/X0HorLAVtAY/S220-s32/cdj1000.jpg
  name: soulache
  profile: https://www.blogger.com/profile/07291404251193359567
  pub: '2008-02-20T15:54:00.000+01:00'
  ref: '366732557268562773'
  type: comment
- date: 20 February 2008 18:05
  html: There are mixed opinions about whether you should use unnumbered interfaces
    or not. <BR/><BR/>If you decide to use them and have multiple areas configured
    on the router, previously you needed a numbered interface in each area. Now you
    can have a single numbered interface serving unnumbered interfaces in multiple
    areas.<BR/><BR/>Sounds confusing? It probably is :)
  id: '3142885509804694835'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_150x150.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-02-20T18:05:00.000+01:00'
  ref: '366732557268562773'
  type: comment
- date: 06 June 2009 11:44
  html: Really interesting. Thanks for letting me know the existence and usage of
    &quot;ip ospf area&quot;.
  id: '636665006689296493'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ludovic Kuty
  profile: https://www.blogger.com/profile/04770655497128144653
  pub: '2009-06-06T11:44:03.550+02:00'
  ref: '366732557268562773'
  type: comment
- date: 22 August 2012 09:29
  html: Thank you so much!! I&#39;m so happy to find this solution, we do use ip unnumbered
    and I&#39;m implementing different areas!
  id: '6650809196762460311'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Mariya
  profile: https://www.blogger.com/profile/10357076188769322020
  pub: '2012-08-22T09:29:00.295+02:00'
  ref: '366732557268562773'
  type: comment
count: 4
id: '366732557268562773'
type: post
url: 2008/02/configure-ospf-on-unnumbered-interfaces.html
