comments:
- comments:
  - date: 08 February 2014 07:55
    html: That is for backwards compatibility incase you were to paste the config
      to an older IOS.
    id: '5160226531105136010'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2014-02-08T07:55:48.803+01:00'
    ref: '3435434779345518626'
    type: comment
  date: 29 February 2008 18:31
  html: This seems to work on most IOS, but I've noticed on Sup720s, 12.2(33)SXH Cisco
    has added VTY 5 - 15.  Even if you standardized all 16 lines, the configuration
    still displays vty 0-4 and 5-15 separately.
  id: '3435434779345518626'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-02-29T18:31:00.000+01:00'
  ref: '2013777735928377198'
  type: comment
count: 2
id: '2013777735928377198'
type: post
url: 2008/02/merging-vty-configurations.html
