comments:
- date: 16 August 2017 11:40
  html: For those who are curious since the post was mainly on the advanced networking
    course, the undergraduate networking textbook that we use is open-source and available
    from http://cnp3book.info.ucl.ac.be
  id: '4661221377255536156'
  image: https://resources.blogblog.com/img/blank.gif
  name: Olivier Bonaventure
  profile: https://inl.info.ucl.ac.be/obo
  pub: '2017-08-16T11:40:11.522+02:00'
  ref: '5869985601157233811'
  type: comment
- date: 17 August 2017 18:26
  html: '&quot;differently-attentive&quot; !<br /><br />Nice concept I just hope my
    router dowsn&#39;t catch it ...'
  id: '3492084540763747'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2017-08-17T18:26:35.889+02:00'
  ref: '5869985601157233811'
  type: comment
count: 2
id: '5869985601157233811'
type: post
url: 2017/08/teach-ipv6-first-and-automate-deployment.html
