comments:
- date: 06 June 2007 19:58
  html: Does anybody know if there is the possibility to override the upstream DNS
    server's TTL value?<BR/>Sometimes, DNS queries are being answered with a TTL value
    of 0, and the router does not store them (or marks them as expired the second
    they arrive). So the router will send out a query to the same host the next time.
    Is there any remedy against this?<BR/>Thanks alot for your help!
  id: '6045443853186595612'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-06-06T19:58:00.000+02:00'
  ref: '4202874090402335237'
  type: comment
- date: 07 June 2007 13:46
  html: As far as I'm aware, IOS cannot do that. Usually there's a good reason the
    reply is sent back with TTL=0 (for example, multi-server load balancing implemented
    with DNS).
  id: '8515450073291737960'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2007-06-07T13:46:00.000+02:00'
  ref: '4202874090402335237'
  type: comment
- date: 08 June 2007 00:49
  html: OK then -- thanks alot for your answer!
  id: '5484718804770942603'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-06-08T00:49:00.000+02:00'
  ref: '4202874090402335237'
  type: comment
- date: 28 September 2008 01:26
  html: I have set up caching dns server on a Cisco 876. Problem is that requests
    are accepted on all interfaces, including the outside interface. What's a good
    method to limit the router to only handle requests arriving on specific interfaces?
    Thanks!
  id: '3475055786473492945'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-09-28T01:26:00.000+02:00'
  ref: '4202874090402335237'
  type: comment
- date: 28 September 2008 17:04
  html: '@Anonymous#3: Inbound access list (ACL) on the outside interface(s). <BR/><BR/>Having
    an ACL that blocks all unwanted traffic is mandatory on interfaces connected to
    a public network (for example, the Internet).'
  id: '2643701243019696443'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-09-28T17:04:00.000+02:00'
  ref: '4202874090402335237'
  type: comment
- date: 26 March 2011 12:08
  html: actually ACLs are not looked at when using the ip dns server on IOS<br /><br
    />best way i have found is to set up NAT on the outside interface, and just NAT
    all incoming traffic on port 53 to a dummy address
  id: '978747522643661672'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2011-03-26T12:08:53.837+01:00'
  ref: '4202874090402335237'
  type: comment
count: 6
id: '4202874090402335237'
type: post
url: 2007/05/dns-configuration.html
