comments:
- date: 10 June 2010 12:17
  html: and after you install RA and DHCPv6 you find out that it only works &quot;out
    of the box&quot; on Windows Vista and Windows 7. For it to work on Windows XP
    or Ubuntu Linux you must install another dhcpv6 client.<br /><br />one would expect
    that 15+ years of IPv6 development would clarify and simplify those &quot;simple
    tasks&quot;, but no....<br /><br />Those things might work ok for some lab rats
    and ipv6 enthusiast, but &quot;Janez Novak&quot;  8-) just &quot;wants it to work&quot;
    (TM) - no installs, no configs and no manual configuration of either IP address
    OR rDNS server...
  id: '185090020424846380'
  image: https://resources.blogblog.com/img/blank.gif
  name: J
  profile: null
  pub: '2010-06-10T12:17:17.000+02:00'
  ref: '5429002792802926926'
  type: comment
- date: 10 June 2010 21:52
  html: SLAAC --&gt; RFC 4862 (updates RFC 2462)<br />RFC 5006 (EXP) will probably
    be rewritten and put on the ztandards track (see IETF work in progress in 6man
    wg)
  id: '4829544609653301896'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mo7sen
  profile: null
  pub: '2010-06-10T21:52:34.000+02:00'
  ref: '5429002792802926926'
  type: comment
- date: 13 June 2010 08:45
  html: Fixed the SLAAC RFC#. Thank you!
  id: '7706547130973559464'
  image: https://resources.blogblog.com/img/blank.gif
  name: RT(F)M
  profile: null
  pub: '2010-06-13T08:45:39.000+02:00'
  ref: '5429002792802926926'
  type: comment
- date: 13 June 2010 08:46
  html: Fixed the SLAAC RFC#. Thank you!
  id: '2459060320856636583'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-06-13T08:46:20.000+02:00'
  ref: '5429002792802926926'
  type: comment
- date: 17 November 2010 08:20
  html: Problem is that some people wanted stateless IPv6 address autoconfiguration,
    and others wanted stateful. So somehow you need to express that policy to the
    end-nodes as to what to use. RAs do this. You could add a default gateway option
    to DHCPv6, and stop RA emitting routers from announcing themselves as default
    routers by setting the router lifetime to zero. But you&#39;re going to have need
    a SLAAC verses DHCPv6 conveyance mechanism regardless - and as RAs serve this
    purpose, why not use RAs to express that policy as well as announce a default
    router. In other words, the root cause of this situation is the dual and conflicting
    requirements of stateless and stateful addressing. I don&#39;t mind either of
    them too much, although I prefer stateless, but would have much preferred one
    or the other methods of address configuration, just not both. *DONT_KNOW*
  id: '6600168052017829417'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mark
  profile: null
  pub: '2010-11-17T08:20:10.000+01:00'
  ref: '5429002792802926926'
  type: comment
- date: 17 November 2010 09:03
  html: As most of the people trying to deploy IPv6 in production networks have found
    out, today you need BOTH - DHCPv6 to tell you the DNS server&#39;s address and
    RA to tell you who the default router is. One or the other could be used to set
    the host&#39;s IPv6 address.
  id: '8171670593405544735'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-11-17T09:03:03.000+01:00'
  ref: '5429002792802926926'
  type: comment
- date: 08 March 2011 01:26
  html: I think you&#39;ve missed my point. How are you going to tell end-nodes to
    use stateful DHCPv6 OR stateless (SLAAC)? If you don&#39;t automate that via a
    link based announcement and/or request/response protocol of some sort, the only
    option left is manual end-node configuration - not practical in a large number
    of cases. RAs could be better described as &quot;IPv6 addressing model and parameter
    configuration protocol&quot;. Routers are a logical device to perform this function,
    and using their announcements to convey default router information is also a reasonable
    optimisation if they&#39;re going to be making periodic announcements or responding
    to solicitations for addressing configuration information anyway. Note that if
    you set the router lifetime in an RA to zero, then end-nodes won&#39;t use the
    router as a default gateway, yet can still use the information in them e.g. PIO,
    for addressing model etc. configuration.<br /><br />The main reason people seem
    to say they want to use stateful DHCPv6 is that they want to record MAC address
    / IPv6 address mappings for audit purposes. I think that can easily be achieved
    in the stateless model by having a router (or another appropriate device) notice
    when DAD is initially occurring, tentatively place that end-node information in
    the neighbor cache if it doesn&#39;t conflict with existing entries, and then
    have NUD generate a SNMP trap when the address is determined to be not a duplicate,
    and have NUD genarate another SNMP trap when the neighbor cache entry is removed.
    Since it would be quite simple to create audit logs of address usage in a stateless
    model using this method, I think DHCPv6 for addressing mostly just exists because
    &quot;that&#39;s how hit works in IPv4&quot;. A shame really, it seems like the
    most popular criticism of IPv6 is support for the two different addressing configuration
    models.
  id: '335720264521260018'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mark
  profile: null
  pub: '2011-03-08T01:26:47.026+01:00'
  ref: '5429002792802926926'
  type: comment
- date: 08 March 2011 08:30
  html: Mark, I understand all you&#39;re saying and I agree with most of it. However,
    I still claim it&#39;s stupid you need BOTH SLAAC and stateless DHCPv6 (to pass
    DNS server address) if you want to auto-configure your end hosts. <br /><br />I
    know the new RFCs are out, but yet again, why did it take 10+ years to realize
    the problem ... and when will we have them available in all desktop OS where they
    matter most?
  id: '3289304536738213608'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2011-03-08T08:30:06.856+01:00'
  ref: '5429002792802926926'
  type: comment
count: 8
id: '5429002792802926926'
type: post
url: 2010/06/ipv6-autoconfiguration-too-many-cooks.html
