comments:
- date: 21 June 2019 10:36
  html: Why should the configuration contain &quot;holes&quot; to begin with? I mean
    with holes in it something would be broken. What problem are they trying to solve?
  id: '5344640510359481823'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Anonymous
  profile: https://www.blogger.com/profile/17892204563666956100
  pub: '2019-06-21T10:36:34.883+02:00'
  ref: '5288933114762390821'
  type: comment
- date: 21 June 2019 15:21
  html: 'The holes I mentioned relate to &quot;parts of the configurations you&#39;re
    not sure about&quot;. <br /><br />Say that you&#39;re running your network with
    configuration A and you need to change its behavior for some reason. Perhaps you
    want to increase the amount of load balancing or prevent some transit traffic.
    For the first requirement, you know that you&#39;ve to modify the link weights
    somehow (to get ECMP) and, for the second one, you know that you&#39;ve to adapt
    your route-maps (to tag/drop routes accordingly). What you do with NetComplete
    is &quot;highlight&quot;/&quot;create a hole&quot; for the weights/route-map in
    your existing configuration A and then ask it to &quot;fill them in&quot; so that
    the resulting configuration meets the requirements: i.e. it load balances and
    prevents transit traffic.<br /><br />I agree with you that &quot;holes&quot; is
    a perhaps a badly chosen term here: &quot;parts to change&quot; is perhaps a better
    way to understand it?<br /><br />Hope it clarifies, if not, please shoot again!!<br
    /><br />Laurent'
  id: '2019271054042510630'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Laurent Vanbever
  profile: https://www.blogger.com/profile/03583813630260845993
  pub: '2019-06-21T15:21:59.161+02:00'
  ref: '5288933114762390821'
  type: comment
- date: 21 June 2019 17:38
  html: Thanks for the clarification. It resembles the batfish project (also originally
    developed by universities) and it remindes me of an intent based networking system
    (probably software defined). Is it used in production networks? What vendors do
    you support?
  id: '6005663115140549400'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Anonymous
  profile: https://www.blogger.com/profile/17892204563666956100
  pub: '2019-06-21T17:38:38.312+02:00'
  ref: '5288933114762390821'
  type: comment
- date: 25 June 2019 13:44
  html: '&gt; &quot;holes&quot; is a perhaps a badly chosen term here: &quot;parts
    to change&quot; is perhaps better<br /><br />Intent Based !<br />:)<br />'
  id: '7009642151256906347'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Albert Siersema
  profile: https://www.blogger.com/profile/04847257511165693348
  pub: '2019-06-25T13:44:45.484+02:00'
  ref: '5288933114762390821'
  type: comment
count: 4
id: '5288933114762390821'
type: post
url: 2019/06/device-configuration-synthesis-with.html
