comments:
- comments:
  - date: 10 October 2015 14:14
    html: I didn&#39;t say it was uncoordinated. I also don&#39;t have to agree with
      &quot;let&#39;s burn them till there&#39;s (almost) nothing left for the latecomers&quot;
      approach.
    id: '7970262578236024523'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2015-10-10T14:14:25.759+02:00'
    ref: '121591224123491053'
    type: comment
  date: 09 October 2015 22:50
  html: Why do you say ARIN&#39;s approach was totally uncontrolled?  It&#39;s the
    approach the community wanted.
  id: '121591224123491053'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Frank Bulk
  profile: https://www.blogger.com/profile/02004215342995023858
  pub: '2015-10-09T22:50:01.079+02:00'
  ref: '7330988840378562726'
  type: comment
count: 2
id: '7330988840378562726'
type: post
url: 2015/10/enterprise-content-over-ipv6-deployment.html
