comments:
- date: 24 April 2018 09:35
  html: In my opinion your Ansible for Networking Engineers webinar is a little bit
    outdated regarding Ansible. When will you update it?
  id: '8284354044279975470'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2018-04-24T09:35:28.310+02:00'
  ref: '6407771926072099285'
  type: comment
- date: 24 April 2018 21:21
  html: Hello my Anonymous friend ;) You probably know I prefer facts over opinions,
    so it would be nice to get a list a few things you feel are missing. I&#39;m aware
    of one or two (like XML parsing in 2.5), would love to see what you find most
    interesting.<br /><br />I also have to wonder why you&#39;re hiding yourself behind
    an opinionated anonymous comment. People with access to the material usually send
    me a direct email with actionable feedback.
  id: '2307283387803555988'
  image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2018-04-24T21:21:46.338+02:00'
  ref: '6407771926072099285'
  type: comment
count: 2
id: '6407771926072099285'
type: post
url: 2018/04/configuration-templating-could-be-huge.html
