comments:
- date: 08 August 2016 12:09
  html: Deployement error ? I&#39;d say protocol design error.<br /><br />Their system
    consisted of 8 servers. Thee servers worked together as one system. So I am sure
    there was network communication between them. Thus there was a protocol. A proprietary
    protcol at the application layer.<br /><br />They changed their protocol. They
    changed the meaning of one bit (the power peg flag). But supposedly their 8 servers
    were not able to figure out that one of them was talking an old version of their
    proprietary protocol. This was the root of their problem.<br /><br />They could
    have had a protocol-version in their packet-header. They could have used TLV-encoding
    instead of fixed-size, fixed-location, fixed-meaning encoding. They could have
    done version negotiating during connection establishment. They could have done
    something. But it seems they did nothing at their own protocol-level to prevent
    these incompatabilities.<br />
  id: '6028850434016284317'
  image: https://resources.blogblog.com/img/blank.gif
  name: Henk
  profile: null
  pub: '2016-08-08T12:09:15.970+02:00'
  ref: '9048316691753879272'
  type: comment
- date: 08 August 2016 13:37
  html: 'As it always happens in such cases: many small mistakes led to one big disaster.
    it is not about automation, but about proper design and supervision on all stages.
    if they would have installed 8th server correctly the would still have been sitting
    on the time bomb waiting for the right circumstances to explode'
  id: '4246992541543548567'
  image: https://lh4.googleusercontent.com/-o93KW7lXB7g/AAAAAAAAAAI/AAAAAAAAT2M/kMZMYGqE934/s32-c/photo.jpg
  name: Romans Fomicevs
  profile: https://www.blogger.com/profile/14849647498700907117
  pub: '2016-08-08T13:37:31.862+02:00'
  ref: '9048316691753879272'
  type: comment
- date: 08 August 2016 21:44
  html: What if the mistake was embedded into the automation process/tool(designed
    by humans) in the first place. Now you have a video series titled &quot;Automation
    Gone Wild&quot; <br /><br />
  id: '8182853660216345886'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: jeff sicuranza
  profile: https://www.blogger.com/profile/07267516785767923381
  pub: '2016-08-08T21:44:38.777+02:00'
  ref: '9048316691753879272'
  type: comment
- comments:
  - date: 10 August 2016 17:28
    html: I think both Hank and yourself missed the point. Yes, there are many things
      that could have been made more resilient (I totally agree with Hank&#39;s remarks),
      and who knows how many skeletons were hidden in those closets, BUT expecting
      a human to repeat a long and convoluted process flawlessly eight times in a
      row borders on insanity.<br /><br />Listen to this podcast http://blog.ipspace.net/2014/11/flipit-cloud-orchestrating-it-as.html
      if you want to hear more details from people who had to solve a similar problem.
    id: '6257292214112219749'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2016-08-10T17:28:11.047+02:00'
    ref: '149768249332852929'
    type: comment
  - date: 13 August 2016 01:37
    html: 'Well yes, I completely agree with the part involving humans repeating complicated
      processes.<br /><br />I was thinking about processes at all levels, for guys
      managing billions of dollars it looks like they skimped almost everywhere:<br
      />-operational: check-lists (did we do all the servers?), verification by a
      second technician, supervision by a software engineer, monitoring of error messages.<br
      />-change management: you have a backout plan, right?<br />-system design: transaction
      anomaly monitoring with safe-guards (in networking has this is BPDU guard, uni-directional
      link detection, etc.)<br />-management oversight seems lacking<br /><br />The
      point I was trying to make is that automating an incorrect procedure will not
      help and that automation, as a software activity, has all the problems associated
      with software development.<br /><br />'
    id: '9099094295573718034'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: Jimmy G
    profile: https://www.blogger.com/profile/11329035181762386541
    pub: '2016-08-13T01:37:15.919+02:00'
    ref: '149768249332852929'
    type: comment
  date: 10 August 2016 16:47
  html: 'Automation is a powerful tool just like redundancy.<br />By now most network
    engineers have learned that redundancy has its own challenges and is not automatically
    equal to robustness. Similarly, automation does not equate to correctness.<br
    /><br />I can&#39;t agree with Ivan on this one. More automation would not have
    helped at all in this case. More thinking was needed at all levels: design, planning,
    testing, monitoring, system integration, etc. '
  id: '149768249332852929'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Jimmy G
  profile: https://www.blogger.com/profile/11329035181762386541
  pub: '2016-08-10T16:47:43.405+02:00'
  ref: '9048316691753879272'
  type: comment
- date: 10 August 2016 16:49
  html: Its summer, have a look at this most recent trend in factory automation:<br
    /><br />youtu.be/ewNLCkA0oBk?t=110
  id: '3173707067970452256'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2016-08-10T16:49:47.565+02:00'
  ref: '9048316691753879272'
  type: comment
count: 7
id: '9048316691753879272'
type: post
url: 2016/08/and-this-is-why-you-need-automation.html
