comments:
- date: 22 November 2010 09:53
  html: A concern that I would have with this configuration is what would happen if
    the box reloads between 17:01 and 07:59. The default state would mean that the
    route would be up. As the EEM is event-basedd, no event would be triggered until
    the next morning. Routing will then happen over the tunnel during a time frame
    where it shouldn&#39;t. Something like this might be a more robust solution:<br
    /><br />access-list 100 permit ip any any time-range time1<br /> !<br /> route-map
    default permit 10<br /> match ip address 100<br /> set interface Tunnel0<br />
    !<br /> !<br /> time-range time1<br /> periodic daily 8:00 to 17:00<br /> !<br
    /> interface FastEthernet0/0<br /> ip policy route-map default
  id: '4673625721388898601'
  image: https://resources.blogblog.com/img/blank.gif
  name: Terry Pattinson
  profile: null
  pub: '2010-11-22T09:53:31.000+01:00'
  ref: '4614877270503112028'
  type: comment
- date: 22 November 2010 10:14
  html: The Policy based solution is real cool. <br /><br />Regards<br /><br />Jack
  id: '331564802341498213'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2010-11-22T10:14:48.000+01:00'
  ref: '4614877270503112028'
  type: comment
- date: 22 November 2010 23:45
  html: The policy based solution seems to be sending ALL traffic to the Tunnel during
    the time range ignoring the primary route that may be available during this time.<br
    /><br />The original problem, if you see in the post is, &quot;to use the BACKUP
    expensive route during working hours only&quot;.
  id: '6233085048200534757'
  image: https://resources.blogblog.com/img/blank.gif
  name: PayingGuest
  profile: null
  pub: '2010-11-22T23:45:16.000+01:00'
  ref: '4614877270503112028'
  type: comment
- date: 23 November 2010 12:34
  html: Exactly!
  id: '3502633927127043077'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-11-23T12:34:16.000+01:00'
  ref: '4614877270503112028'
  type: comment
- date: 08 December 2011 16:50
  html: can be done on a dynamic configuration of EEM
  id: '8238521652766122270'
  image: https://resources.blogblog.com/img/blank.gif
  name: philipe
  profile: null
  pub: '2011-12-08T16:50:34.310+01:00'
  ref: '4614877270503112028'
  type: comment
count: 5
id: '4614877270503112028'
type: post
url: 2010/11/time-based-static-routes.html
