comments:
- date: 07 December 2007 04:10
  html: Why not use OpenDNS (www.opendns.com) instead of crappy ISP DNS servers?  At
    that rate you gain phishing protection, domain name auto-correction, filtering
    (if you set up an account) and of course much faster and ultra fault tolerance
    by way of anycast usage.  I don't work for or am affiliated in OpenDNS in any
    way, but they sure do rock!
  id: '2312005863255109558'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-12-07T04:10:00.000+01:00'
  ref: '531406339631672132'
  type: comment
- date: 09 December 2007 09:36
  html: Thanks for the hint - I've started using it on my newly-installed Linux box
    (the IOS DNS server would behave strangely when faced with IPv6-related records)
    and it works perfectly ;)
  id: '2971523165373250281'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2007-12-09T09:36:00.000+01:00'
  ref: '531406339631672132'
  type: comment
- date: 24 July 2010 18:19
  html: 'Hi Ivan, <br />I&#39;ve tried your hint and my debug is like your but my
    router doesn&#39;t fix the DNS address in the host table that is:<br /><br />Router#show
    host           <br />Default domain is not set<br />Name/address lookup uses domain
    service<br />Name servers are 255.255.255.255<br /><br />Codes: u - unknown, e
    - expired, * - OK, ? - revalidate<br />       t - temporary, p - permanent<br
    />...<br /><br />Can you help me?'
  id: '3759369621629492113'
  image: https://resources.blogblog.com/img/blank.gif
  name: Giovanni
  profile: null
  pub: '2010-07-24T18:19:44.000+02:00'
  ref: '531406339631672132'
  type: comment
- date: 24 July 2010 18:27
  html: Are you sure the SP is sending you DNS addresses in IPCP reply?
  id: '9134588272961008305'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-07-24T18:27:27.000+02:00'
  ref: '531406339631672132'
  type: comment
- date: 24 July 2010 18:53
  html: Yes, I found it in debug trace
  id: '4741405926163403754'
  image: https://resources.blogblog.com/img/blank.gif
  name: giovanni
  profile: null
  pub: '2010-07-24T18:53:59.000+02:00'
  ref: '531406339631672132'
  type: comment
- date: 24 July 2010 18:56
  html: Yes, I see it in debug trace
  id: '9114235297206677887'
  image: https://resources.blogblog.com/img/blank.gif
  name: giovanni
  profile: null
  pub: '2010-07-24T18:56:46.000+02:00'
  ref: '531406339631672132'
  type: comment
- date: 27 September 2010 13:26
  html: You can also import the ipcp negotiated DNS server(s) into a dhcp profile
    by using:<br />&quot;import all&quot;<br /><br />This means you don&#39;t need
    to run the dns server on the cisco box.<br /><br />Hope that helps!
  id: '1215941070880607393'
  image: https://resources.blogblog.com/img/blank.gif
  name: racitup
  profile: null
  pub: '2010-09-27T13:26:16.000+02:00'
  ref: '531406339631672132'
  type: comment
- date: 17 August 2011 15:30
  html: Very good article, I could fix my problem adding &quot;ppp ipcp dns request&quot;
    in the CPE Dialer interface.<br />Thanks<br />Cassio<br /> :-D
  id: '135111471847738506'
  image: https://resources.blogblog.com/img/blank.gif
  name: Cassio Gomes
  profile: null
  pub: '2011-08-17T15:30:18.357+02:00'
  ref: '531406339631672132'
  type: comment
count: 8
id: '531406339631672132'
type: post
url: 2007/11/configure-dns-servers-through-ipcp.html
