comments:
- date: 01 November 2007 15:15
  html: So show running-config may be substituted by more tftp://local.ip.addr/system:running-config
    ?
  id: '2424370746889260361'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-11-01T15:15:00.000+01:00'
  ref: '2100211679599972778'
  type: comment
- date: 01 November 2007 18:40
  html: Nope, due to TFTP server limitations (or maybe its a 'security' feature) you
    cannot include the path. So you have to use tftp://local-ip-addr/running-config
    or tftp://local-ip-addr/startup-config :)
  id: '6258203377736584792'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2007-11-01T18:40:00.000+01:00'
  ref: '2100211679599972778'
  type: comment
- date: 01 November 2007 18:43
  html: I'm loading my OSes in my lab that way using the loopback adapter...<BR/>didn't
    want to spend the money on more flash... =)<BR/><BR/>boot-start-marker<BR/>boot
    system tftp://192.168.201.10/c3620-ik9o3s7-mz.123-23.bin<BR/>boot-end-marker<BR/>interface
    Loopback0<BR/> ip address 192.168.201.10 255.255.255.255<BR/>tftp-server slot0:c3620-ik9o3s7-mz.123-23.bin
  id: '4834137768650518870'
  image: https://3.bp.blogspot.com/-5bI5_KMtfL4/Ujif2ZjX8rI/AAAAAAAAAkM/N7fNIKBGxAU/s32/42420eb1d29945e9a1c4fd420673030c
  name: Tommy B
  profile: https://www.blogger.com/profile/06257076984949203390
  pub: '2007-11-01T18:43:00.000+01:00'
  ref: '2100211679599972778'
  type: comment
- date: 29 March 2008 12:57
  html: Is it possible to use internal tftp for serving static-bindings file for dhcp-pool?<BR/><BR/>Example:<BR/>static-bindings
    is saved on flash (Soho97 in this case), and configuration<BR/><BR/>tftp-server
    flash1:static-bindings<BR/><BR/>(dhcp pool conf.)<BR/>origin file tftp://local-ip-addr/static-bindings
  id: '4969626444062106556'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-03-29T12:57:00.000+01:00'
  ref: '2100211679599972778'
  type: comment
- date: 31 March 2008 13:35
  html: '@Anonymous: why would you want to do that? Isn''t it simpler to specify <B>origin
    file flash:static-bindings</B>?'
  id: '6624149420241715759'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-03-31T13:35:00.000+02:00'
  ref: '2100211679599972778'
  type: comment
count: 5
id: '2100211679599972778'
type: post
url: 2007/11/download-router-configurations-via-tftp.html
