---
category: [ Automation ]
title: Elastic Stack for Network and Security Engineers
sort_field: name

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

bottom: |
  <div class='info' markdown='1'>When Andrea is not writing about network automation tools
  he's busy automating Cisco ACI environments. To learn more about what he's doing, and
  whether he might be able to help you doing something similar, contact
  him through [email](mailto:andrea.dainese@gmail.com),
  [LinkedIn](https://www.linkedin.com/in/adainese/) or
  on [Twitter](https://twitter.com/adainese).
  </div>

  {{ next }}

intro: |
  This article was written by [Andrea Dainese](https://www.linkedin.com/in/adainese/),
  senior network and security architect, and author of UNetLab (now
  [EVE-NG](http://www.eve-ng.net/) and
  [Route Reflector Labs](http://www.routereflector.com/)).
