comments:
- date: 04 August 2009 12:17
  html: When using RADIUS/Tacacs, there&#39;s a corresponding AV pair (autocmd=x).
    &#39;Username ... autocommand&#39; will work only for local users.<br /><br />http://www.cisco.com/en/US/docs/ios/sec_user_services/configuration/guide/sec_tacacs_attr_vp_ps6441_TSD_Products_Configuration_Guide_Chapter.html
  id: '6491865726099932346'
  image: https://resources.blogblog.com/img/blank.gif
  name: Autumn Aeterna
  profile: null
  pub: '2009-08-04T12:17:30.000+02:00'
  ref: '3207136043394785574'
  type: comment
count: 1
id: '3207136043394785574'
type: post
url: 2009/06/autocommands-in-aaa-environment.html
