comments:
- date: 02 December 2008 17:31
  html: I love this command!
  id: '2198690472919618392'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-12-02T17:31:00.000+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 07 January 2009 09:31
  html: '@anonymous - Love? Get a life :-) But indeed VERY useful.'
  id: '6493216583746678773'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2009-01-07T09:31:00.000+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 30 January 2009 06:02
  html: I'm not near any lab equipment at the moment, so I'll just ask this question:<BR/><BR/>is
    it possible to apply this using the range command?<BR/><BR/>default interface
    range gi1/0/20 - 40<BR/><BR/>Sorry, I would like to have been able to post up
    the result myself.
  id: '9179431697222741446'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2009-01-30T06:02:00.000+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 31 January 2009 09:49
  html: '@Nickwalt: Looking purely at parser help, it looks like you can use the "range"
    keyword.'
  id: '13792923776262707'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2009-01-31T09:49:00.000+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 15 July 2010 04:00
  html: Great tip!  Indeed it works with the &quot;range&quot; command.  I just ran
    it on several ports on an Etherswitch module in a 3725:<br /><br />Rack1SW2(config)#default
    interface range f1/7 - 15<br />Rack1SW2(config)#<br /><br />Worked briliantly.
  id: '3071101492728447056'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2010-07-15T04:00:10.000+02:00'
  ref: '2956352098321199012'
  type: comment
- comments:
  - date: 05 November 2012 23:28
    html: Did you ever get an answer to the Nexus question?
    id: '4531063856042053861'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2012-11-05T23:28:24.591+01:00'
    ref: '7044816047489168139'
    type: comment
  - date: 07 April 2013 09:02
    html: no the nexus serie does not know this command
    id: '4296732333895145399'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2013-04-07T09:02:40.754+02:00'
    ref: '7044816047489168139'
    type: comment
  - date: 14 January 2015 22:46
    html: 'Yes it does<br /><br />System version: 5.2(1)N1(8a)'
    id: '4659957045071460018'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2015-01-14T22:46:57.108+01:00'
    ref: '7044816047489168139'
    type: comment
  date: 21 February 2012 16:26
  html: How about Nexus 5000 ?<br />Ther are no default command available on this
    devices ???
  id: '7044816047489168139'
  image: https://resources.blogblog.com/img/blank.gif
  name: anonym
  profile: null
  pub: '2012-02-21T16:26:22.666+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 15 February 2013 16:32
  html: What is the default command for removing all the information in cisco ASA,
    as we have nameif, security-level, ip address..thanks in advance Mr. Ivan Pepelnjak
  id: '2776078371152092123'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/08490240367248012291
  pub: '2013-02-15T16:32:31.482+01:00'
  ref: '2956352098321199012'
  type: comment
- date: 13 July 2014 17:04
  html: Hi , you can use this command on nexus product from release 6.2<br />
  id: '4648308597268290368'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2014-07-13T17:04:12.331+02:00'
  ref: '2956352098321199012'
  type: comment
- date: 25 May 2017 17:51
  html: no switchport<br />switchport
  id: '856203441721600948'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/15944170364653746075
  pub: '2017-05-25T17:51:31.996+02:00'
  ref: '2956352098321199012'
  type: comment
- date: 25 May 2017 18:40
  html: 'no switchport<br />switchport<br /><br />Converting to L3, then back to L2.
    Removing int config. '
  id: '2125835182822181002'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/15944170364653746075
  pub: '2017-05-25T18:40:21.630+02:00'
  ref: '2956352098321199012'
  type: comment
count: 13
id: '2956352098321199012'
type: post
url: 2007/06/default-interface-configuration-command.html
