comments:
- comments:
  - date: 23 February 2015 23:55
    html: 'nm.  /me opens his eyes a little wider and notices &quot;interface&quot;
      vs &quot;address&quot; '
    id: '9160976006090869677'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2015-02-23T23:55:02.836+01:00'
    ref: '4666175246897357131'
    type: comment
  date: 23 February 2015 23:54
  html: is the &quot;here&#39;s how you do it in quagga&quot; code section a misprint?  looks
    the same as the &quot;normal bgp&quot; code section
  id: '4666175246897357131'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2015-02-23T23:54:08.489+01:00'
  ref: '4753407295072887528'
  type: comment
- comments:
  - date: 13 January 2016 23:17
    html: Ericsson (ex. Redback) also has &quot;neighbor zzzzz internal&quot; in the
      non-vpn contexts, which does not accept &quot;remote-as&quot; in the neighbor
      definition.
    id: '4338307619480001948'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: R.-Adrian F.
    profile: https://www.blogger.com/profile/11418671261451939355
    pub: '2016-01-13T23:17:54.347+01:00'
    ref: '2891155939676359690'
    type: comment
  date: 25 February 2015 08:34
  html: In regard to the &quot;remote-as internal&quot;, Juniper has that. You just
    set the bgp group to &quot;type internal&quot; and it will use your local AS.<br
    /><br />
  id: '2891155939676359690'
  image: https://resources.blogblog.com/img/blank.gif
  name: Sebastian
  profile: http://blog.karotte.org/
  pub: '2015-02-25T08:34:07.811+01:00'
  ref: '4753407295072887528'
  type: comment
- date: 25 February 2015 20:09
  html: COBOL. Now I am curious if someone for a laugh mapped a BGP config to a COBOL
    program.  Identification, Data,Environment, Procedure Divisions with sections
    mapping to BGP sections  etc. LOL
  id: '2596469174179583519'
  image: https://resources.blogblog.com/img/blank.gif
  name: jsicuran
  profile: http://www.amilabs.com
  pub: '2015-02-25T20:09:55.216+01:00'
  ref: '4753407295072887528'
  type: comment
- comments:
  - date: 13 April 2015 19:35
    html: 'This one was really good a decade ago: http://www.ciscopress.com/store/internet-routing-architectures-9781578702336<br
      /><br />Not sure what to recommend these days, but then the basics of BGP haven&#39;t
      changed that much.'
    id: '848732779947798561'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2015-04-13T19:35:44.221+02:00'
    ref: '1893077996134648351'
    type: comment
  date: 13 April 2015 19:13
  html: Hello Ivan (or any one else willing to make a recommendation):<br />What book(s)
    or other resource would you recommend to help learn BGP?<br /><br />Thanks.
  id: '1893077996134648351'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Salman Naqvi
  profile: https://www.blogger.com/profile/11529916018516958539
  pub: '2015-04-13T19:13:38.663+02:00'
  ref: '4753407295072887528'
  type: comment
- comments:
  - date: 07 May 2015 18:08
    html: Local AS number is always configured, so the AS number a router has to send
      in the BGP OPEN message is known. The only change is that the router doesn&#39;t
      check the AS number in the incoming BGP OPEN message but accepts whatever is
      there as the remote AS.
    id: '474084360540477335'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2015-05-07T18:08:06.933+02:00'
    ref: '3681916122970300624'
    type: comment
  - date: 11 May 2015 09:18
    html: Ah yes, it makes perfect sense, thanks Ivan!
    id: '5683015305242548985'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2015-05-11T09:18:41.150+02:00'
    ref: '3681916122970300624'
    type: comment
  date: 07 May 2015 09:58
  html: '&quot;accepts the AS number advertised by the neighbor&quot;<br />What if
    the other side has the same &quot;external&quot; configuration with no AS configured?
    <br />Secondly, does this mean that quagga will only listen to open messages but
    never send them? Because what would happen if it sent an open message w/o ASN?'
  id: '3681916122970300624'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2015-05-07T09:58:15.424+02:00'
  ref: '4753407295072887528'
  type: comment
- comments:
  - date: 01 April 2016 12:04
    html: 'Obvious it depends heavily on your design. <br /><br />Best case: one subnet
      per ToR switch. <br />Worst case: one host route per VM.'
    id: '3941950048533215220'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2016-04-01T12:04:44.881+02:00'
    ref: '2115500946114192095'
    type: comment
  date: 22 March 2016 07:54
  html: Ivan<br />Any comments on the number of ebgp routes a TOR white box should
    hold considering a medium-large data centre? Agree with vary will design..
  id: '2115500946114192095'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/13166994775481013804
  pub: '2016-03-22T07:54:52.668+01:00'
  ref: '4753407295072887528'
  type: comment
- date: 24 March 2016 22:42
  html: 'Are the keywords &quot;external&quot; or &quot;internal&quot; even necessary
    ? '
  id: '838677999178992917'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Krish
  profile: https://www.blogger.com/profile/02209871772930896757
  pub: '2016-03-24T22:42:37.692+01:00'
  ref: '4753407295072887528'
  type: comment
- date: 21 June 2018 20:09
  html: 'Intrigued by the documented simplicity, I wanted to find out how far this
    can be reproduced in Junos and what is going on at the IETF about learning remote
    peer AS numbers. There is an I-D https://datatracker.ietf.org/doc/draft-acee-idr-lldp-peer-discovery/
    that uses LLDP. But no implementation in Junos yet. Long story short, I ended
    up using IPv6 RA to cook up a working prototype using on box automation and wrote
    a blog post about it: https://marcelwiget.wordpress.com/2018/06/21/bgp-over-unnumbered-interfaces-automated/ '
  id: '8396553026917070233'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Marcel
  profile: https://www.blogger.com/profile/00402219321437186516
  pub: '2018-06-21T20:09:02.667+02:00'
  ref: '4753407295072887528'
  type: comment
count: 14
id: '4753407295072887528'
type: post
url: 2015/02/bgp-configuration-made-simple-with.html
