comments:
- date: 20 February 2015 14:03
  html: Great timing! I&#39;ll be implementing BGP for the first time ever in production
    next month. Looking forward to reading this.
  id: '7458536561976027757'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/11890997522662363216
  pub: '2015-02-20T14:03:37.079+01:00'
  ref: '6381624987670101725'
  type: comment
- date: 20 February 2015 23:09
  html: Congrats Ivan on the RFC.
  id: '1423455362669630984'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2015-02-20T23:09:42.369+01:00'
  ref: '6381624987670101725'
  type: comment
- date: 24 February 2015 11:26
  html: I wonder why don&#39;t they (IETF) ever choose some interesting format for
    publishing RFCs to make those valuable and interesting :)<br /><br />Evil CCIE
  id: '1612189863411449669'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: A Network Artist
  profile: https://www.blogger.com/profile/06314916176190119200
  pub: '2015-02-24T11:26:59.039+01:00'
  ref: '6381624987670101725'
  type: comment
- date: 26 February 2015 06:38
  html: Congratulations, this is a great doc!
  id: '7644682829996637852'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: bill
  profile: https://www.blogger.com/profile/14808936148378009872
  pub: '2015-02-26T06:38:18.107+01:00'
  ref: '6381624987670101725'
  type: comment
count: 4
id: '6381624987670101725'
type: post
url: 2015/02/rfc-7454-bgp-operations-and-security.html
