comments:
- date: 07 February 2011 11:08
  html: I&#39;ve used rtr or ip-sla or whatever<br />it&#39;s called this week to
    do this.
  id: '1023984011111413943'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2011-02-07T11:08:21.557+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 13:07
  html: We just use the Anritsu traffic generator/sniffer/load tester that we have
    in our lab  :-D
  id: '1140747449182680681'
  image: https://resources.blogblog.com/img/blank.gif
  name: PG
  profile: null
  pub: '2011-02-07T13:07:45.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 16:07
  html: For windows machines in a test-lab, I&#39;ve made this little app:<br /><br
    />http://www.asknet.dk/page_1292871817508.html<br /><br /> :)
  id: '7732143617523140086'
  image: https://resources.blogblog.com/img/blank.gif
  name: Kelvin Dam
  profile: null
  pub: '2011-02-07T16:07:50.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 16:26
  html: One word - awesome! )
  id: '4986146083802254273'
  image: https://resources.blogblog.com/img/blank.gif
  name: And
  profile: null
  pub: '2011-02-07T16:26:19.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 17:29
  html: For different (Type of service) value in extended ping, can you show me other
    value for different IP precedence.  Thanks !!!  ;)
  id: '1493145179362145193'
  image: https://resources.blogblog.com/img/blank.gif
  name: Newbie
  profile: null
  pub: '2011-02-07T17:29:06.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 20:01
  html: Newbie, take a look at http://www.netcontractor.pl/download/QoS%20Values%20Calculator%20v2.pdf
  id: '2719049357035714238'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2011-02-07T20:01:15.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 20:08
  html: I would have configured different local (loopback) interfaces for differentially
    sourcing the pings.<br />...And, depending on your needs, don&#39;t forget to
    mention ip sla  ;)
  id: '7935798012355396221'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2011-02-07T20:08:08.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 07 February 2011 20:12
  html: '@Newbie<br />This should come in handy: http://blog.webdir.bg/tos-to-dscp-mapping/'
  id: '3552364468676430914'
  image: https://resources.blogblog.com/img/blank.gif
  name: Sinisa
  profile: null
  pub: '2011-02-07T20:12:40.000+01:00'
  ref: '7773587833071848224'
  type: comment
- date: 25 January 2013 11:28
  html: It&#39;s available now :<br /><br />GAV#ping 1.1.1.1 tos ?<br />  &lt;1-255&gt;  Type
    of service<br /><br />thanks to CSCtn94681    Ability to apply the priority markings
    in the Ping command <br />finally resolved in 2012.
  id: '6168180272258637330'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: xabrouck
  profile: https://www.blogger.com/profile/08629115121576798324
  pub: '2013-01-25T11:28:59.540+01:00'
  ref: '7773587833071848224'
  type: comment
count: 9
id: '7773587833071848224'
type: post
url: 2011/02/changing-ip-precedence-values-in-router.html
