comments:
- date: 15 June 2013 02:51
  html: Jetty does SPDY Server Pushes. Additionally, it will automatically figure
    out which resources to push after the first request.<br /><br />http://webtide.intalio.com/2012/10/spdy-push-demo-from-javaone-2012/
  id: '5364338376427682370'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: James Harr
  profile: https://www.blogger.com/profile/10939581110701056032
  pub: '2013-06-15T02:51:30.908+02:00'
  ref: '7299378938389825199'
  type: comment
- comments:
  - date: 26 July 2013 05:30
    html: I did - let&#39;s reinvent TCP, but run it over UDP or it won&#39;t go through
      firewalls ;)
    id: '4242595359659868902'
    image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2013-07-26T05:30:46.057+02:00'
    ref: '224437579590910858'
    type: comment
  date: 25 July 2013 23:32
  html: Ivan, have you heard of QUIC protocol?<br /><br />https://lwn.net/Articles/558826/<br
    />https://en.wikipedia.org/wiki/QUIC<br />http://blog.chromium.org/2013/06/experimenting-with-quic.html
  id: '224437579590910858'
  image: https://resources.blogblog.com/img/blank.gif
  name: Marcos
  profile: null
  pub: '2013-07-25T23:32:21.812+02:00'
  ref: '7299378938389825199'
  type: comment
count: 3
id: '7299378938389825199'
type: post
url: 2013/06/will-spdy-solve-web-application.html
