comments:
- date: 25 August 2007 22:54
  html: Thanks man!<BR/>This really helped me get on with BGP!
  id: '1895678087632724813'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: jekyl
  profile: https://www.blogger.com/profile/01729676697229250730
  pub: '2007-08-25T22:54:00.000+02:00'
  ref: '6912780825666758710'
  type: comment
count: 1
id: '6912780825666758710'
type: post
url: 2007/04/bgp-configuration-resources.html
