comments:
- comments:
  - date: 02 May 2015 00:00
    html: Made my day (just what I needed sitting at Las Vegas airport waiting for
      a delayed flight).<br /><br />Thanks a million!
    id: '7554671670628533601'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2015-05-02T00:00:19.388+02:00'
    ref: '1596328474604787555'
    type: comment
  date: 01 May 2015 23:56
  html: Do ALFs like to eat CATs (Complex Application Transactions)
  id: '1596328474604787555'
  image: https://resources.blogblog.com/img/blank.gif
  name: Brian Christopher Raaen
  profile: http://www.brianraaen.com
  pub: '2015-05-01T23:56:42.011+02:00'
  ref: '7188586962778134257'
  type: comment
- comments:
  - date: 02 May 2015 15:25
    html: I&#39;ve had the same experience many times with nvr&#39;s using ports 2001
      and 2002.<br /><br />There is also the legendary esmtp inspection which effectively
      destroys the protocol. More like esmtp f**kup
    id: '4999463366848974064'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2015-05-02T15:25:01.222+02:00'
    ref: '7540430330083596036'
    type: comment
  - date: 04 May 2015 16:26
    html: 'I remember a similar issue with the server-side email filtering language
      SIEVE: in its early days, it used 2000/tcp by default, but later did move to
      4190/tcp. 2000/tcp is still in use by legacy configurations, but later became
      assigned to Cisco&#39;s Skinny protocol. As a result, an ASA in place may accept
      the connection (client thinks &quot;server accepts the tcp connection), the
      ASA doesn&#39;t read skinny protocol packets and hence closes the connection
      (clients thinks &quot;server closed connection&quot;). Of course, the SIEVE
      server doesn&#39;t ever see an incoming connection from that client - and so
      one can easily spend days debugging this.'
    id: '6270142190018322821'
    image: https://lh3.googleusercontent.com/-YeurV_9_3q0/AAAAAAAAAAI/AAAAAAAAIyc/EtdE3UESGWs/s32-c/photo.jpg
    name: Anders Henke
    profile: https://www.blogger.com/profile/04441771667073544925
    pub: '2015-05-04T16:26:20.373+02:00'
    ref: '7540430330083596036'
    type: comment
  date: 02 May 2015 03:39
  html: My one experience with &#39;fix&#39;ups was on a Cisco ASA doing remote user
    vpn..  When I installed it I never disabled the default inspection stuff (What
    harm could they do?).<br /><br />Much later, after what should have been an uneventful
    update on some windows servers, no one could access email (MAPI) over the vpn.  Turns
    out the update changed a default rpc port or something causing the ASA to think
    the traffic was malformed skinny packets, and drop it.<br /><br />
  id: '7540430330083596036'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Justin A
  profile: https://www.blogger.com/profile/07567730572096907480
  pub: '2015-05-02T03:39:31.056+02:00'
  ref: '7188586962778134257'
  type: comment
count: 5
id: '7188586962778134257'
type: post
url: 2015/05/alf-application-layer-fixup.html
