---
category: [ Automation ]
title: Network Automation Data Model Optimization
sort_field: name
upcoming_articles: true

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

bottom: |
  ## More Information

  * The source code for this article is [published on GitHub](https://github.com/ipspace/ansible-examples/tree/master/Data-Models)
  * You'll find an introduction to data models used in network automation, data model
    optimizations, and data transformation between high-level and low-level data models
    in [Network Automation Concepts](https://www.ipspace.net/Network_Automation_Concepts) webinar
  * To learn more about using data models in network automation solutions check out
    [Module 3](https://my.ipspace.net/bin/list?id=NetAutSol&module=3) of our
    [Building Network Automation Solutions](https://www.ipspace.net/Building_Network_Automation_Solutions)
    online course.

  {{ next }}
