comments:
- date: 19 January 2020 22:51
  html: "Hi Ivan,<br />you might like this paper from 2012: The ironies of automation\u2026\
    \ still going strong at 30?<br />https://www.researchgate.net/publication/231537926_The_ironies_of_automation_still_going_strong_at_30"
  id: '6590636405412716494'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: pgs
  profile: https://www.blogger.com/profile/17475307680165417427
  pub: '2020-01-19T22:51:19.089+01:00'
  ref: '410834556045514696'
  type: comment
count: 1
id: '410834556045514696'
type: post
url: 2020/01/must-read-ironies-of-automation.html
