comments:
- date: 31 August 2015 20:53
  html: great read, more like that please
  id: '111626573116233866'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2015-08-31T20:53:47.006+02:00'
  ref: '3125673844131333570'
  type: comment
- comments:
  - date: 01 September 2015 22:51
    html: '&quot;Also thinking about obscure situations improve overall security.&quot;<br
      /><br />No it doesn&#39;t. <br /><br />Also, you are a security guy, that&#39;s
      why you feel that way. It hurts to be humbled. Security research is a joke.
      The real smart guys are on the other side.'
    id: '4706457307742247893'
    image: https://resources.blogblog.com/img/blank.gif
    name: Anonymous
    profile: null
    pub: '2015-09-01T22:51:38.015+02:00'
    ref: '3857574685605469397'
    type: comment
  date: 01 September 2015 08:49
  html: No, this read didn&#39;t make me enjoy my morning coffee ...<br />The first
    page only shows an ignorant As...hole that just can&#39;t accept anything he doesn&#39;t
    understand. If he can&#39;t think of any reason why someone does sports, why doesn&#39;t
    he just ignore that instead of insulting them?<br />The rest reads like the whining
    of a huffish child that was told that it didn&#39;t do good.<br />That&#39;s what
    reaction I would expect from the &quot;researcher&quot; that was responsible for
    the Windows 95 security and now wants to sugarcoat what he did.<br />No, security
    is not only black or white. There are nuances, and luckily not all researchers
    think like whats shown in James Mickens blogpost. Also thinking about obscure
    situations improve overall security. And probably sometime in the future one of
    these security researchers that he bashes will find a way that Mr. Mickens can
    remember a strong password. And all without being killed by the Mossad ...
  id: '3857574685605469397'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2015-09-01T08:49:41.352+02:00'
  ref: '3125673844131333570'
  type: comment
- date: 04 September 2015 09:33
  html: Hyperbole isn&#39;t for everyone, personally I love his writing and also his
    presentations links widely available through your favorite search engine
  id: '3695962666843409825'
  image: https://resources.blogblog.com/img/blank.gif
  name: "P\xE4r Bj\xF6rklund"
  profile: null
  pub: '2015-09-04T09:33:05.380+02:00'
  ref: '3125673844131333570'
  type: comment
count: 4
id: '3125673844131333570'
type: post
url: 2015/08/must-read-james-mickens-on-security.html
