comments:
- date: 24 December 2008 13:24
  html: Does the link work for anyone?  I get a corrupt file that can't be opened.
  id: '5844893545834199542'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-12-24T13:24:00.000+01:00'
  ref: '3926811931227035076'
  type: comment
- date: 24 December 2008 13:46
  html: I just clicked the "Download the document ..." link in IE7 and FF2 after clearing
    their caches. <BR/><BR/>The first page that opens contains a snapshot of the PDF
    in JPG format. If I click the snapshot or the link below it, I get the PDF in
    the browser window rendered by Adobe Acrobat.<BR/><BR/>What's your experience?
    What browser/OS platform are you using?<BR/><BR/>Ivan
  id: '7632889486441583392'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-12-24T13:46:00.000+01:00'
  ref: '3926811931227035076'
  type: comment
- date: 24 December 2008 15:58
  html: Ivan,<BR/>My apologies....I just tried IE7 and it worked.  I normally use
    FF3 with the pdf downloader plugin.  <BR/>Thanks.
  id: '4219266459212074610'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-12-24T15:58:00.000+01:00'
  ref: '3926811931227035076'
  type: comment
- date: 24 December 2008 15:58
  html: Hey, cheat sheets are my territory, Pepelnjak!<BR/><BR/>I kid. =) Beautifully
    done! (Downloaded with no problem for me.)
  id: '2126340230566903032'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-12-24T15:58:00.001+01:00'
  ref: '3926811931227035076'
  type: comment
- date: 24 December 2008 17:18
  html: Thanks, Stretch !!! Coming from an expert, it means even more to me ;)
  id: '2702707057112788170'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-12-24T17:18:00.000+01:00'
  ref: '3926811931227035076'
  type: comment
- date: 05 August 2009 08:42
  html: Hi Ivan<br />You have some misprint in MPLS_VPN_cheatsheet.pdf document.<br
    />Please verify section &quot;Running BGP with the customer&quot; and &quot;Static
    routes&quot;
  id: '1667082155132757939'
  image: https://resources.blogblog.com/img/blank.gif
  name: "\u0413\u043E\u0441\u0442\u044C"
  profile: null
  pub: '2009-08-05T08:42:06.000+02:00'
  ref: '3926811931227035076'
  type: comment
- date: 05 August 2009 21:10
  html: Got it. Thanks. Will fix.
  id: '4925502474587479511'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2009-08-05T21:10:44.000+02:00'
  ref: '3926811931227035076'
  type: comment
- date: 16 August 2009 05:04
  html: I have IOS c2600-adventerprisek9-mz.124-18a but when I try to us mpls ip in
    an interface IOS is not giving me the mpls option...any advice? :(
  id: '7435048176027744843'
  image: https://resources.blogblog.com/img/blank.gif
  name: Guest
  profile: null
  pub: '2009-08-16T05:04:09.000+02:00'
  ref: '3926811931227035076'
  type: comment
- date: 16 August 2009 07:24
  html: Obviously MPLS is no longer available on a 2600 (and it was never officially
    supported anyway). It was working for quite some time with earlier IOS releases,
    but it looks like they ran into code size limits and something had to go.
  id: '4985701668188311573'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2009-08-16T07:24:25.000+02:00'
  ref: '3926811931227035076'
  type: comment
- date: 28 August 2011 19:48
  html: It seems the file is missing
  id: '1848165622660908857'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2011-08-28T19:48:25.763+02:00'
  ref: '3926811931227035076'
  type: comment
- date: 28 August 2011 20:04
  html: Fixed. Thanks!
  id: '1741516087679503301'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2011-08-28T20:04:25.473+02:00'
  ref: '3926811931227035076'
  type: comment
count: 11
id: '3926811931227035076'
type: post
url: 2008/12/basic-mpls-vpn-design-configuration.html
