comments:
- date: 23 July 2008 08:12
  html: Hvala Pipi, tole bo lepo olajsalo dolocene stvari.
  id: '8461016149053510121'
  image: https://resources.blogblog.com/img/blank.gif
  name: Aljosa Us
  profile: null
  pub: '2008-07-23T08:12:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 23 July 2008 11:46
  html: Very interesting.<BR/>Just wondering....does the ospf output include any interface
    specific config too?
  id: '4528736071821562270'
  image: https://bp3.blogger.com/_1XnhmB73_-E/R5JTHI0fREI/AAAAAAAAAAk/k0-U8I95ilQ/S220-s32/ccieUseLogo.jpg
  name: "Tassos (CCIE\u2122 #19858)"
  profile: https://www.blogger.com/profile/04512662084752743003
  pub: '2008-07-23T11:46:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 23 July 2008 13:16
  html: strange thing.....it seems that my ios version doesn't support this feature...
    but, but, but... I have quite new ios :D<BR/><BR/>c181x-advipservicesk9-mz.124-15.T3.bin<BR/><BR/>rtr#show
    runn ?<BR/>  all         Configuration with defaults<BR/>  brief       configuration
    without certificate data<BR/>  class-map   Show class-map information<BR/>  flow        Global
    Flow configuration subcommands<BR/>  full        full configuration<BR/>  interface   Show
    interface configuration<BR/>  linenum     Display line numbers in output<BR/>  map-class   Show
    map class information<BR/>  policy-map  Show policy-map information<BR/>  ssid        Show
    Dot11 SSID information<BR/>  view        View options<BR/>  vlan        Show L2
    VLAN information<BR/>  |           Output modifiers
  id: '4018621327069112631'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-07-23T13:16:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 23 July 2008 14:23
  html: Is this just a rollup of the "section" output modifier?
  id: '2527146236675585967'
  image: https://resources.blogblog.com/img/blank.gif
  name: Aaron Conaway
  profile: http://aconaway.com
  pub: '2008-07-23T14:23:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 23 July 2008 16:45
  html: '@tassos: no, the "show running router xxx"  contains only the routing process
    configuration.<BR/><BR/>@anonymous: This feature only works in 12.2SRB/C. It''s
    not yet integrated in 12.4.<BR/><BR/>@aaron: the "section" output modifier is
    a grep-like filter that is applied AFTER the output is already generated, which
    can take a long time if you have large configuration. The "show running xxx" command
    generates just the necessary part of the router configuration and is thus significantly
    faster.'
  id: '3780713840090217111'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_150x150.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-07-23T16:45:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 25 July 2008 18:10
  html: '"This feature was introduced in software images for the <B>Cisco 7600 series</B>
    in Release 12.2(33)SRB"<BR/><BR/>Probably should have included that piece of important
    information. :|'
  id: '94168460115207403'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Whisper
  profile: https://www.blogger.com/profile/00963478939764648991
  pub: '2008-07-25T18:10:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 25 July 2008 18:53
  html: It works on a 7200 in 12.2(33)SRC. You didn't think I have a 7600 to play
    with, did you?
  id: '2637428617388079942'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_150x150.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-07-25T18:53:00.000+02:00'
  ref: '3570954389497010956'
  type: comment
- date: 27 December 2011 20:23
  html: great article.
  id: '8014669987759019500'
  image: https://resources.blogblog.com/img/blank.gif
  name: cma1kep
  profile: null
  pub: '2011-12-27T20:23:34.650+01:00'
  ref: '3570954389497010956'
  type: comment
count: 8
id: '3570954389497010956'
type: post
url: 2008/07/router-configuration-partitioning.html
