comments:
- date: 21 October 2008 16:41
  html: Back when I was teaching CCNP courses some years ago, I had a student who
    got really upset when I told him there was no good reason to use the matching
    inverse-mask method. He simply refused to believe that any other method was acceptable,
    and questioned my competence for even suggesting anything else. I thought he was
    a little too much emotional investment in IOS configurations. :-)
  id: '1681374708641611698'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Jay Swan
  profile: https://www.blogger.com/profile/02571029118821999072
  pub: '2008-10-21T16:41:00.000+02:00'
  ref: '7727886380664991101'
  type: comment
- date: 21 October 2008 17:03
  html: I just have a slight quibble with one of your recommendations.  In the second
    to last configuration, you recommend making sure that your links are in separate
    IP ranges, and using the network command to match those ranges, but in the last
    (complex) example, you recommend using the area command on the individual interfaces.  Personally,
    I have always tried to make sure that I design the network to fit that middle
    scenario - that way, when I add a new site (and corresponding interface to the
    HQ/Hub router), the new interface is automatically in the right area.  This discipline
    also helps keep the network summarizable, to keep the size of the routing tables
    down.  There may be some exceptions, but I think it's better to treat those as
    exceptions, than to abandon good design just because the network is 'complex'
    (especially since almost everyone thinks their network is complex).
  id: '1909488907748721408'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2008-10-21T17:03:00.000+02:00'
  ref: '7727886380664991101'
  type: comment
- date: 25 October 2008 19:52
  html: '@js: I''ve also seen students like that :)<BR/><BR/>@Anonymous: You''re absolutely
    correct. I''ve reworded the "complex scenarios" section. This problem might arise
    if there''s no clear IP addressing design (for example, nobody was willing to
    pay for it :), if the network has grown "organically" or if the network is being
    migrated from another routing protocol (for example, from EIGRP) to OSPF.'
  id: '1407168007743788689'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-10-25T19:52:00.000+02:00'
  ref: '7727886380664991101'
  type: comment
- date: 23 November 2009 05:36
  html: Pls provide the best book to easily understand OSPF,BGP and IP/MPLS.am working
    with service provider in Dubai
  id: '1197300963512651844'
  image: https://resources.blogblog.com/img/blank.gif
  name: yahya Misbah
  profile: null
  pub: '2009-11-23T05:36:35.000+01:00'
  ref: '7727886380664991101'
  type: comment
count: 4
id: '7727886380664991101'
type: post
url: 2008/10/ospf-area-configuration-best-practices.html
