comments:
- date: 24 September 2016 07:34
  html: Any idea which is the best open orchestration system available with open config
    support?
  id: '808885352054004584'
  image: https://lh6.googleusercontent.com/-VD_tWrWRSA8/AAAAAAAAAAI/AAAAAAAAA4s/9UZ8BRjxDRM/s32-c/photo.jpg
  name: Shivlu Jain
  profile: https://www.blogger.com/profile/18067647693954733854
  pub: '2016-09-24T07:34:00.789+02:00'
  ref: '2474975586744514825'
  type: comment
- comments:
  - date: 27 November 2017 12:54
    html: There&#39;s NETCONF module in Ansible. Never tested it though...<br /><br
      />&quot;Adding it to NAPALM doesn&#39;t make sense as they&#39;re treading on
      each others toes&quot; &lt;&lt; Have you looked at OpenConfig in NAPALM?
    id: '1455717465594719117'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2017-11-27T12:54:29.876+01:00'
    ref: '5878079382481201255'
    type: comment
  date: 27 November 2017 12:34
  html: I&#39;d love to see support for this in Salt or Ansible.  Does anyone know
    of active projects working on this?  Adding it to NAPALM doesn&#39;t make sense
    as they&#39;re treading on each others toes, but some python module to help integrate
    this with Salt/Ansible would be great.
  id: '5878079382481201255'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: James Luther
  profile: https://www.blogger.com/profile/08290089638451647921
  pub: '2017-11-27T12:34:06.355+01:00'
  ref: '2474975586744514825'
  type: comment
count: 3
id: '2474975586744514825'
type: post
url: 2016/09/juniper-is-serious-about-openconfig-and.html
