comments:
- comments:
  - date: 17 October 2018 10:05
    html: It&#39;s a well-known problem, and a source of infinite fun for Fernando
      Gont (who devised numerous variants of this attack every time the $vendors claimed
      to fix the problem)... eventually resulting in RFC 6980 and RFC 7113.<br /><br
      />Never tracked how many vendors implemented it correctly though. Any feedback
      highly welcome.
    id: '4761301829650862093'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2018-10-17T10:05:28.978+02:00'
    ref: '7544928421266448893'
    type: comment
  date: 17 October 2018 09:57
  html: In the production networks I manage IPv6 isn&#39;t used at all and most of
    my experience using IPv6 is lab based so apologies if im massively behind the
    curve here, but did I read that correctly that IPv6 fragmentation can be used
    as a tool to circumvent RA Guard?
  id: '7544928421266448893'
  image: https://resources.blogblog.com/img/blank.gif
  name: John
  profile: https://noiproute.wordpress.com/
  pub: '2018-10-17T09:57:37.999+02:00'
  ref: '8520872716072199302'
  type: comment
- date: 17 October 2018 10:00
  html: Thanks for that gold nugget. Eric did also a great job with his &#39;IPv6
    Security&#39; book although it&#39;s a bit old, it&#39;s still holds value. I&#39;ve
    read the whole book.
  id: '8207818081018171414'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2018-10-17T10:00:24.362+02:00'
  ref: '8520872716072199302'
  type: comment
count: 3
id: '8520872716072199302'
type: post
url: 2018/10/must-read-operational-security.html
