comments:
- comments:
  - date: 05 February 2016 10:10
    html: We&#39;ll fix this small challenge ;)<br /><br />The materials will eventually
      find their way into webinars. The roadmap is already online http://www.ipspace.net/Roadmap/Network_Automation_webinars
      but it&#39;s mostly empty at the moment.<br /><br />I&#39;ll probably run another
      workshop in US sometime in autumn, and it will most likely be a combo of SDN/SDDC/Network
      Automation materials spread over a week.<br /><br />There might also be an online
      course covering the same topics. Register into my SDN mailing list and I&#39;ll
      keep you posted ;)
    id: '7735528762767368605'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2016-02-05T10:10:25.354+01:00'
    ref: '7056948930523541675'
    type: comment
  date: 04 February 2016 22:40
  html: All of those are of great interest to me, but I&#39;m in the US - will the
    talk be recorded and available somewhere?  Or available to buy?  These are exactly
    the kinds of questions I&#39;m trying to answer in our network right now.
  id: '7056948930523541675'
  image: https://lh4.googleusercontent.com/-ZaKSzYautLc/AAAAAAAAAAI/AAAAAAAAAyg/qIpCGW9HrsM/s32-c/photo.jpg
  name: Keller Giacomarro
  profile: https://www.blogger.com/profile/13710171886493626963
  pub: '2016-02-04T22:40:08.420+01:00'
  ref: '4603422481561042541'
  type: comment
- comments:
  - date: 05 February 2016 12:41
    html: Not a problem - they can register for &quot;1 Day of Troopers Trainings&quot;
      @ $990 and attend just my workshop.<br /><br />I might run a longer (2-day)
      version of this workshop, or a combo of SDN + network automation workshop somewhere
      in Europe, but can&#39;t promise anything.
    id: '3958447536568800249'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2016-02-05T12:41:43.374+01:00'
    ref: '5673087962334092502'
    type: comment
  date: 05 February 2016 11:11
  html: Aloha,<br />will you also run another workshops in Europe as well?<br />The
    trooper is a full 2days conference,<br />and I know some guys, who are only interested
    to see you Ivan and especially this topics like network automation, SDN, Yang,
    Ansible, Tail-F,...<br />
  id: '5673087962334092502'
  image: https://resources.blogblog.com/img/blank.gif
  name: Marcel
  profile: null
  pub: '2016-02-05T11:11:36.434+01:00'
  ref: '4603422481561042541'
  type: comment
count: 4
id: '4603422481561042541'
type: post
url: 2016/02/upcoming-event-network-automation.html
