comments:
- date: 16 January 2007 13:49
  html: "Hello again.<br />And this one too :)<br />I want to ask you to grant for\
    \ me the permission to translate your article \"Router Configuration Management\
    \ \u2026 Too Good to be True?\" into russian and publish it in cisco_ru (http://community.livejournal.com/cisco_ru/profile)\
    \ - russian Cisco LiveJournal community, in my blog (http://romik-g.livejournal.com/)\
    \ and on http://www.opennet.ru/ site, which is one of the largest russian system\
    \ and network administration info server."
  id: '5397623286524766906'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-01-16T13:49:00.000+01:00'
  ref: '116499658954780513'
  type: comment
count: 1
id: '116499658954780513'
type: post
url: 2006/12/router-configuration-management-too.html
