comments:
- date: 17 July 2012 01:53
  html: The webinars are execellent. I went through the iPv6 and Virtulization recordings.
    I recently completed an IPv6 project for a US DOE agency. And i recommended Ivan&#39;s
    classes to their staff as part of my own post project training curriculem.
  id: '2892914259983301989'
  image: https://resources.blogblog.com/img/blank.gif
  name: jsicuran
  profile: http://www.amilabs.com
  pub: '2012-07-17T01:53:45.572+02:00'
  ref: '756100665193310473'
  type: comment
- date: 03 August 2012 17:56
  html: Agreed, fire drills are expensive and problematic.  <br /><br />A planned
    migration is the most functional, most economical and least impactful way to do
    anything - especially IPv6.
  id: '560143362558135931'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/18433992102893508928
  pub: '2012-08-03T17:56:51.470+02:00'
  ref: '756100665193310473'
  type: comment
- date: 03 August 2012 23:56
  html: +1 to TJ Evans&#39; comment.
  id: '2407518222381591127'
  image: https://resources.blogblog.com/img/blank.gif
  name: Chris V.
  profile: null
  pub: '2012-08-03T23:56:22.108+02:00'
  ref: '756100665193310473'
  type: comment
count: 3
id: '756100665193310473'
type: post
url: 2012/07/analyst-driven-ipv6-deployment.html
