comments:
- date: 02 June 2011 18:16
  html: Nice script but  how about the reverse - real configs -&gt; create dynagen
    topo? any good pointers?<br /><br />-mateusz
  id: '1981501818595355133'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mat
  profile: null
  pub: '2011-06-02T18:16:04.774+02:00'
  ref: '2380215224429862872'
  type: comment
- date: 02 June 2011 18:20
  html: How would you figure out what&#39;s connected in real world based on configs
    only?
  id: '6470726326932399849'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2011-06-02T18:20:12.798+02:00'
  ref: '2380215224429862872'
  type: comment
- date: 02 June 2011 18:28
  html: ip addresses - links have /30 or /31 on them? Multi router links like vlan
    trunks or FR serial links ... manual probably.
  id: '2546842016827407093'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mat
  profile: null
  pub: '2011-06-02T18:28:24.539+02:00'
  ref: '2380215224429862872'
  type: comment
- date: 02 June 2011 18:30
  html: Unnumbered interfaces?
  id: '6556617109652286934'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2011-06-02T18:30:21.656+02:00'
  ref: '2380215224429862872'
  type: comment
- date: 02 June 2011 18:57
  html: there are 100s of exceptions I guess
  id: '8935905835685771011'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mat
  profile: null
  pub: '2011-06-02T18:57:10.535+02:00'
  ref: '2380215224429862872'
  type: comment
count: 5
id: '2380215224429862872'
type: post
url: 2008/04/create-initial-router-configurations.html
