comments:
- comments:
  - date: 16 June 2016 09:45
    html: That would make great sense (because we had some amazing discussions), but
      alas we didn&#39;t record them.
    id: '983507958161940592'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2016-06-16T09:45:21.901+02:00'
    ref: '4647513949236631572'
    type: comment
  date: 16 June 2016 01:01
  html: By any chance, do you have the recordings of these sessions. Thanks
  id: '4647513949236631572'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Unknown
  profile: https://www.blogger.com/profile/14273731945429483575
  pub: '2016-06-16T01:01:54.061+02:00'
  ref: '1668773488694793691'
  type: comment
count: 2
id: '1668773488694793691'
type: post
url: 2016/05/dont-miss-day-full-of-sdn-security.html
