comments:
- date: 19 January 2009 09:18
  html: If you use the default list you don't have to make any changes to the Console
    or VTY lines. They will automatically use the default aaa list. For example:<BR/><BR/>aaa
    new-model<BR/>aaa authentication login default group local<BR/><BR/>You can also
    use this in your corporate network:<BR/><BR/>aaa new-model<BR/>aaa authentication
    login default group TACACS+ local<BR/><BR/>No passwords on lines, no authentication
    commands on lines. Nice and clean.
  id: '4059814507247764828'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Nick Walton
  profile: https://www.blogger.com/profile/05865993197685449327
  pub: '2009-01-19T09:18:00.000+01:00'
  ref: '3596724434681386131'
  type: comment
- date: 12 April 2010 00:26
  html: if i have two local users , and want to restrict one of them to telnet access
    ,how can i do that ?
  id: '2009753358389725604'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2010-04-12T00:26:55.000+02:00'
  ref: '3596724434681386131'
  type: comment
- date: 08 July 2010 14:23
  html: i mistakenly configure AAA client (Cisco Catalyst 3560) without <br />aaa
    authentication login default group tacacs+ LOCAL<br />and a local user name and
    password is existing on device but now i could not access that switch.. <br />niether
    through remote access / console port.<br />so is there any way to recover password
    for that switch?<br /><br />Thanks in advance
  id: '8391093393047040635'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ali Murtaza Solangi
  profile: null
  pub: '2010-07-08T14:23:57.000+02:00'
  ref: '3596724434681386131'
  type: comment
- date: 08 July 2010 14:46
  html: The first link will probably give you what you need:<br /><br />http://www.google.com/search?q=catalyst+3560+recover+password
  id: '231364105495462555'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-07-08T14:46:04.000+02:00'
  ref: '3596724434681386131'
  type: comment
- date: 20 October 2011 14:22
  html: When you configure aaa authentication login MyList local, does the Radius
    server have to be configured with the group name &quot;MyList&quot; also?  In
    addition, I have aaa configured as:<br />radius-server host 111.111.111.111<br
    />radius-server host 222.222.222.222<br />radius-server key PASSWORDXXXXXXXXXXXXXXXXXX<br
    />aaa new-model<br />aaa authenication login default radius local<br /><br />With
    these configs in place and the necessary configs on the server, I am able to log
    into the devices via ssh but can no longer console into devices locally.  Do I
    need to add:<br />Line con 0<br />login auth default <br /><br />Will this allow
    me to log in via the console port and authenticate via radius if necessary?<br
    />Also, I have an emergency username configured at priv level 0 secret.  if AAA
    fails, will I still be able to access the device as login local is no longer an
    option under line con 0 since aaa has been configured.
  id: '4559238919832279990'
  image: https://resources.blogblog.com/img/blank.gif
  name: JoAnn
  profile: null
  pub: '2011-10-20T14:22:21.027+02:00'
  ref: '3596724434681386131'
  type: comment
count: 5
id: '3596724434681386131'
type: post
url: 2007/03/configure-local-authentication-with-aaa.html
