comments:
- date: 23 February 2017 23:38
  html: In my new capacity (IAB member) I have started number of initiatives to facilitate
    better alignment between IETF and OC.<br />POSIX vs XSD regexp dialects as the
    first item, more to come. Will be updating you from time to time
  id: '8082728545770089453'
  image: https://4.bp.blogspot.com/-Jm8onWGyM0M/WoYk1lJ1zuI/AAAAAAAAAy8/aU73FTiTCFUgsnYdYVJ8cf3PRUZqGlKOACK4BGAYYCw/s32/jeff_tantsura.jpg
  name: Jeff Tantsura
  profile: https://www.blogger.com/profile/17193851449183304827
  pub: '2017-02-23T23:38:04.652+01:00'
  ref: '6463895024680688415'
  type: comment
count: 1
id: '6463895024680688415'
type: post
url: 2017/02/openconfig-from-basics-to.html
