comments:
- comments:
  - date: 13 February 2017 15:28
    html: 'Interface naming: I don&#39;t see a problem, interfaces always had names
      ;)<br /><br />AS Path Length versus AS Numbers: apart from a few corner cases
      the AS path length is compared, not the actual AS numbers in the AS path.<br
      /><br />Public/Private ASN: Sure - when you want to advertise your internal
      addresses straight to public Internet.'
    id: '999012002790203593'
    image: https://lh3.googleusercontent.com/-ZIhwz6bLuK0/AAAAAAAAAAI/AAAAAAAAFtg/mLtCQ3p4_0E/s32-c/photo.jpg
    name: Ivan Pepelnjak
    profile: https://www.blogger.com/profile/13457151406311272386
    pub: '2017-02-13T15:28:23.836+01:00'
    ref: '8913194757671650666'
    type: comment
  date: 13 February 2017 08:25
  html: 'Hi Dinesh/Ivan<br /><br />If BGP uses interface instead of neighbor IP,do
    we specialy introduce a new configuration for identifying interface names. Current
    devices have interface names as 4/51 or such like that , how do we achieve interface
    naming conventions in router world . In Server Qagga world it looks easy. <br
    /><br />ASP path length and ASN numbers are two different attributes in choosing
    BGP Path chosing. <br /><br />Making a decision based on AS path length and making
    a desicion based on AS path numbers are two different scenarios. <br /><br />AS
    path length is default one. Policies match AS path numbers for actual mulltipathing.
    Which is a viable solution. <br /><br />DO we peer Public ASN with Private ASN
    peering in any scenario inside BGP. '
  id: '8913194757671650666'
  image: https://2.bp.blogspot.com/_oBcXcN9kPY0/SksfBucujXI/AAAAAAAAAMA/IsTo-cg4RGQ/S220-s32/05042009(018)000.jpg
  name: HUMOROUS HEMANTH
  profile: https://www.blogger.com/profile/08900264515934620482
  pub: '2017-02-13T08:25:56.640+01:00'
  ref: '4717317801404724806'
  type: comment
- date: 14 February 2017 06:58
  html: '@Ivan Is there a name that we can specifiy for an interface for example ethernet
    1/20/3 can i call it as  just &quot;Port 1&quot; . Is there acommand to it in
    Cisco , Juniepr and Arista devices. '
  id: '5564290669407609512'
  image: https://2.bp.blogspot.com/_oBcXcN9kPY0/SksfBucujXI/AAAAAAAAAMA/IsTo-cg4RGQ/S220-s32/05042009(018)000.jpg
  name: HUMOROUS HEMANTH
  profile: https://www.blogger.com/profile/08900264515934620482
  pub: '2017-02-14T06:58:03.495+01:00'
  ref: '4717317801404724806'
  type: comment
count: 3
id: '4717317801404724806'
type: post
url: 2017/02/video-simplify-bgp-configurations.html
