comments:
- date: 09 January 2017 03:16
  html: 'FYI: https://www.packet.net/promo/virl/<br /><br />Packet has teamed with
    the Cisco VIRL team to offer bare metal server nodes that deploy in minutes and
    allow you to effortlessly deploy VIRL.'
  id: '1045729133207826793'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mark Milstein
  profile: https://twitter.com/epiloque
  pub: '2017-01-09T03:16:58.000+01:00'
  ref: '2268616661581481777'
  type: comment
count: 1
id: '2268616661581481777'
type: post
url: 2016/11/testing-ansible-playbooks-with-cisco.html
