---
category: [ Docker ]
title: Docker Networking for Container-Based Services
sort_field: name
upcoming_articles: true

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

#upcoming:
#- Multi-Subnet Servers
#- Challenges of Multi-Subnet Clients

bottom: |
  {{ next }}
  <hr/>
  ## More Information

  If you're new to Docker, start with
  [Introduction to Docker](https://www.ipspace.net/Introduction_to_Docker) webinar;
  if you'd like to learn more about Docker networking, explore the
  [Docker Networking Deep Dive](https://www.ipspace.net/Docker_Networking_Deep_Dive)
  webinar. Both webinars are part of
  [ipSpace.net subscription](http://www.ipspace.net/Subscription).

  The source code for all the examples used in this article is
  [available on Github](https://github.com/ipspace/docker-examples/).

  All printouts in this article were created on a Ubuntu host running Docker
  engine version 19.03.12.

