comments:
- date: 12 February 2007 15:35
  html: I did ask for this!  It is exactly the solution I was looking for.  You are
    great! tnx
  id: '7448658117639836146'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-02-12T15:35:00.000+01:00'
  ref: '125174053808352601'
  type: comment
- date: 14 February 2007 18:18
  html: Hi Ivan,  nice web site!  I have a question a little off topic but sort of
    related;  many books and web sites state that the Administrative Distance of a
    static route pointing to an outgoing interface is 0,  however IOS shows that the
    AD is 1.  For example, this excerpt from Routing TCP/IP Vol 1 Second Edition,  Jeff
    Doyle,  Pg. 99;  "For example, IPv4 static routes pointing to a next-hop address
    have an administrative distance of 1, and static routes referencing an exit interface
    have an administrative distance of 0". At some point in the past was this true?  Do
    you know the history behind this?  Thanks.
  id: '7415263930194907319'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Matt
  profile: https://www.blogger.com/profile/14542348828560810624
  pub: '2007-02-14T18:18:00.000+01:00'
  ref: '125174053808352601'
  type: comment
- date: 20 February 2007 20:00
  html: All static routes are treated equally since (at least) IOS release 12.2. <A
    HREF="http://ioshints.blogspot.com/2007/02/not-all-static-routes-were-created.html"
    REL="nofollow">Here are the details</A>.
  id: '2870677643741207483'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_100x100.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2007-02-20T20:00:00.000+01:00'
  ref: '125174053808352601'
  type: comment
- date: 09 August 2007 19:19
  html: 'I have two link''s: 1024kbps e 512kbps, ppp. In teh 512k there''s no traffic!!
    Then, when i make this configuration the traffic coming! But only in one direction
    of the 512k link. What''s wrong? Thank''s'
  id: '3705298736253471322'
  image: https://resources.blogblog.com/img/blank.gif
  name: Anonymous
  profile: null
  pub: '2007-08-09T19:19:00.000+02:00'
  ref: '125174053808352601'
  type: comment
- date: 17 August 2007 10:47
  html: You need to have similar configuration on both ends of the link (static routes
    affect only outgoing traffic). Also make sure that you have CEF switching enabled
    on both ends, otherwise the fast-switching code will use only a single path.
  id: '3742294819781563406'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_100x100.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2007-08-17T10:47:00.000+02:00'
  ref: '125174053808352601'
  type: comment
- date: 12 March 2008 04:42
  html: Hello Ivan, I am going to attempt to apply your fancy static route method
    to my problem, but I wanted to throw a problem at you to see if I have missed
    some things.  I have a router which has two unequal paths being provided by the
    Satellite provider.  I connect to their network via GIG0/0 and GIG0/1.  The rates
    are 9mb and 3 mb respectively.  They allow me to use my own IP addresses due to
    the use of MPLS on their part.  I traverse their network to my remote router.  Right
    now I am only using the 9mb link with the 3mb as a failover.  I want to load balance
    across these two links but I have VOIP traffic.  I believe that if I allow this
    traffic along with the data to go through the load balancing, I will end up with
    to much jitter on the call because it will split routes.  Is there a way to force
    the VOIP to use one link while still running the load sharing protocol such as
    EIGRP with a variance.  As a side problem, I would also still want failover if
    I was to lose one link.  So the VOIP would have to be able to move.  Basically
    everyone needs to get out regaurdless of whether both links are up or just one
    with VOIP always having priority.  I have setup GRE tunnels on my one link to
    make the router see the ethernet connection for what it really is (9mb), but we
    really want to use the full 12mb or pretty close.
  id: '6509305358833376682'
  image: https://lh3.googleusercontent.com/zFdxGE77vvD2w5xHy6jkVuElKv-U9_9qLkRYK8OnbDeJPtjSZ82UPq5w6hJ-SA=s35
  name: Michael
  profile: https://www.blogger.com/profile/18121966832548559692
  pub: '2008-03-12T04:42:00.000+01:00'
  ref: '125174053808352601'
  type: comment
- date: 17 March 2008 13:18
  html: '@Michael: if you use CEF, packets belonging to a single source-destination
    address pair (or a single TCP/UDP session, if you configure it so) will always
    go over the same path, so there will be no extra jitter within a single VoIP call.'
  id: '6070814698628572165'
  image: https://i72.photobucket.com/albums/i181/ixpepeln/krneki/Pipi_150x150.jpg
  name: Ivan Pepelnjak
  profile: https://www.blogger.com/profile/13457151406311272386
  pub: '2008-03-17T13:18:00.000+01:00'
  ref: '125174053808352601'
  type: comment
- date: 25 August 2010 19:13
  html: Hello Ivan, nice site thank you.<br /><br />a question related to the topic,
    i saw the person before me is having it similar so I want to conclude on it:<br
    /><br />I have a GRE tunnel accros two devices with two paths in between. because
    the src/dst are always the same I cannot make the traffic flow over both lines
    on one of the devices. The router on which this works is 2821 with 12.4(15)T7
    with &quot;ip load-sharing per-packet&quot; on the interfaces, and the other side
    is CISCO7613 with 12.2(33r)SRB4 with only option of &quot;ip load-sharing per-destination&quot;
    on its ATM subinterfaces . Both have CEF enabled. the 7600 is sending out only
    on a single line<br /><br />thanks<br />Nick
  id: '2639267955047042589'
  image: https://resources.blogblog.com/img/blank.gif
  name: nikolay popgeorgiev
  profile: null
  pub: '2010-08-25T19:13:21.000+02:00'
  ref: '125174053808352601'
  type: comment
- date: 21 September 2010 14:05
  html: awesome ..<br /><br />I was hunting for this solution..  :)<br />But how dod
    U know the bogus routing part? I dont think it is somewhere written or posted..
    <br /><br />Thank You<br />Chetan
  id: '2122101717010337068'
  image: https://resources.blogblog.com/img/blank.gif
  name: Chetan
  profile: null
  pub: '2010-09-21T14:05:37.000+02:00'
  ref: '125174053808352601'
  type: comment
- date: 23 September 2010 19:04
  html: Recursive routing table lookup. Present in IOS since (at least) 9.0 SW.
  id: '3231097096832662799'
  image: https://resources.blogblog.com/img/blank.gif
  name: Ivan Pepelnjak
  profile: null
  pub: '2010-09-23T19:04:41.000+02:00'
  ref: '125174053808352601'
  type: comment
- date: 03 February 2012 16:44
  html: hello, thanks for the information<br /><br />  I have a cisco 2801 router
    and I want to connect two ADSL links on it and balance the load but not that kind
    of IOS that team would need or if I would be useful?
  id: '8989537679655945090'
  image: https://resources.blogblog.com/img/blank.gif
  name: Mar
  profile: null
  pub: '2012-02-03T16:44:50.984+01:00'
  ref: '125174053808352601'
  type: comment
- date: 23 March 2014 12:19
  html: 'Zdravo Ivane, interesuje me postoji li mogucnost da moju ADSL konekciju koja
    dolazi na ruter, i odatle se racva na nekoliko djelova (1 kabal i vise wireless
    uredjaja) mogu podesiti tako da konekcija koju ja koristim ima fiksnu velicinu,
    recimo pola konekcije. Dok bi ostali korisnici dijelili drugi dio. Nadam se da
    sam bio jasan, Blagodarim. '
  id: '6797670754931141048'
  image: https://3.bp.blogspot.com/_xxUTbilrZT4/SyYD8PKqf0I/AAAAAAAAABE/wmKWGcus1-A/S220-s33/imm_2009_10_17_00_47_50_29.JPG
  name: Amer O.
  profile: https://www.blogger.com/profile/13003283972527927740
  pub: '2014-03-23T12:19:52.534+01:00'
  ref: '125174053808352601'
  type: comment
count: 12
id: '125174053808352601'
type: post
url: 2007/02/unequal-load-split-with-static-routes.html
