comments:
- date: 03 March 2008 15:42
  html: Hello,<BR/><BR/>On specific platforms you need to specify the day, month,
    year.<BR/><BR/>12.2(46a):<BR/><BR/>alias exec 991 clock set 08:00:00 3 march 2008
  id: '7249438036823660063'
  image: https://resources.blogblog.com/img/blank.gif
  name: fropert
  profile: null
  pub: '2008-03-03T15:42:00.000+01:00'
  ref: '8441751928613558619'
  type: comment
count: 1
id: '8441751928613558619'
type: post
url: 2008/03/debugging-time-based-configuration.html
